[tool.poetry]
name = "ososedki_dl"
version = "0.1.0"
description = "Blazing bulk web scraper for leak sites"
license = "GPL-3.0-only"
authors = ["Alejandro González Momblán <agelrenorenardo@gmail.com>"]
readme = "README.md"
repository = "https://github.com/YisusChrist/ososedki_dl"

[tool.poetry.dependencies]
python = "^3.12"
aiofiles = "^24.1.0"
aiohttp = "^3.9.5"
beautifulsoup4 = "^4.12.2"
core-helpers = {git = "https://github.com/YisusChrist/core_helpers"}
fake-useragent = "^1.5.1"
platformdirs = "^4.2.2"
requests = "^2.31.0"
requests-pprint = "^1.0.1"
rich = "^13.5.3"
tldextract = "^5.1.2"
validators = "^0.22.0"

[tool.poetry.group.dev.dependencies]

[tool.poetry.group.types.dependencies]
types-aiofiles = "^24.1.0.20241221"
types-beautifulsoup4 = "^4.12.0.20241020"
types-pygments = "^2.18.0.20240506"
types-requests = "^2.32.0.20241016"

[tool.poetry.scripts]
ososedki_dl = "ososedki_dl.__main__:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
