blank_issues_enabled: false
contact_links:
    - name: Contributing to ososedki_dl
      url: https://github.com/YisusChrist/ososedki_dl/blob/main/CONTRIBUTING.md
      about: Guidelines for how to report an issue.
    - name: Support
      url: https://github.com/YisusChrist/ososedki_dl/discussions
      about: Ask the community for support
    - name: Documentation
      url: https://github.com/YisusChrist/ososedki_dl/wiki
      about: Many questions might be already answered here.
