name: ❓ Question
description: If you have a question about how to use codewars-solver that's not well covered by our documentation
labels: ["question"]
assignees:
    - YisusChrist
body:
    - type: markdown
      attributes:
          value: |
              ## Self Check
              - Look for similar errors in existing [GitHub Issues](https://github.com/YisusChrist/codewars-solver/issues?q=is%3Aissue) (open or closed).
              - Take a look at the [documentation](https://github.com/YisusChrist/codewars-solver/wiki) for help.
    - type: textarea
      validations:
          required: true
      attributes:
          label: Describe the bug
          description: A clear description of what the bug is.
    - type: textarea
      validations:
          required: true
      attributes:
          label: Steps to reproduce
          description: |
              Steps to reproduce the problem.
          placeholder: |
              For example:
              1. Execute with options '...'
              2. Check output '...'
              3. See error
    - type: textarea
      validations:
          required: true
      attributes:
          label: Expected behavior
          description: A brief description of what should happen.
    - type: textarea
      attributes:
          label: Screenshots and recordings
          description: |
              If applicable, add screenshots to help explain your problem. You can also record an asciinema session: https://asciinema.org/
    - type: input
      validations:
          required: true
      attributes:
          label: OS / Linux distribution
          placeholder: Windows 10, Ubuntu 20.04, Arch Linux, macOS 10.15...
    - type: input
      validations:
          required: true
      attributes:
          label: codewars-solver version
          description: Run `codewars-solver -v` to check.
          placeholder: "1.0"
    - type: textarea
      attributes:
          label: Additional context
          description: Add any other context about the problem here. This can be path, platform, shell...
