name: Auto-merge Dependabot PRs

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    uses: YisusChrist/github-actions-workflows/.github/workflows/automerge-dependabot-prs.yml@main
    secrets: inherit
