name: Release

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    uses: YisusChrist/github-actions-workflows/.github/workflows/release.yml@main
    with:
      python-version: "3.12"
    secrets: inherit
